---
apiVersion: v1
kind: Secret
metadata:
  name: booklore-db-secrets
type: Opaque
stringData:
  mysql-root-password: "{{ randAlphaNum 32 | b64enc | quote }}"
  mysql-password: "{{ randAlphaNum 32 | b64enc | quote }}"
