---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemera
  labels:
    app: ephemera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemera
  template:
    metadata:
      labels:
        app: ephemera
    spec:
      containers:
        - name: ephemera
          image: ghcr.io/orwellianepilogue/ephemera:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8286
          env:
            - name: BASE_URL
              value: https://ephemera.koudijs.me
            - name: AA_BASE_URL
              value: https://annas-archive.in
            - name: LG_BASE_URL
              value: https://libgen.ac
            - name: FLARESOLVERR_URL
              value: http://localhost:8191
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - mountPath: /app/data
              name: ephemera-data
            - mountPath: /app/downloads
              name: ephemera-downloads
            - mountPath: /app/ingest
              name: ephemera-ingest
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_HTML
              value: "false"
            - name: CAPTCHA_SOLVER
              value: "none"
            - name: TZ
              value: "Europe/Amsterdam"
      volumes:
        - name: ephemera-data
          persistentVolumeClaim:
            claimName: ephemera-data
        - name: ephemera-downloads
          persistentVolumeClaim:
            claimName: ephemera-downloads
        - name: ephemera-ingest
          persistentVolumeClaim:
            claimName: ephemera-ingest
