---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: docker.io/filebrowser/filebrowser:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            # Apps
            - mountPath: /srv/music
              name: swing-music-data
            - mountPath: /srv/soulseek
              name: slskd-data
            - mountPath: /srv/audiobooks
              name: audiobookshelf-audiobooks
            - mountPath: /srv/books
              name: booklore-books
            - mountPath: /srv/bookdrop
              name: booklore-bookdrop
            - mountPath: /srv/ephemera-downloads
              name: ephemera-downloads
            - mountPath: /srv/ephemera-ingest
              name: ephemera-ingest
            # Filebrowser
            - mountPath: /database
              name: filebrowser-vol-database
            - mountPath: /config
              name: filebrowser-vol-config
      volumes:
        # Apps
        - name: swing-music-data
          persistentVolumeClaim:
            claimName: swing-music-data
        - name: slskd-data
          persistentVolumeClaim:
            claimName: slskd-data
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
        - name: booklore-books
          persistentVolumeClaim:
            claimName: booklore-books
        - name: booklore-bookdrop
          persistentVolumeClaim:
            claimName: booklore-bookdrop
        - name: ephemera-downloads
          persistentVolumeClaim:
            claimName: ephemera-downloads
        - name: ephemera-ingest
          persistentVolumeClaim:
            claimName: ephemera-ingest
        # Filebrowser
        - name: filebrowser-vol-database
          persistentVolumeClaim:
            claimName: filebrowser-database
        - name: filebrowser-vol-config
          persistentVolumeClaim:
            claimName: filebrowser-config
